```{r}
#| warning: false
#| message: false

library("tidyverse")
library("cowplot")
library("broom")
library("table1")
library("ggplot2")
```

```{r}
#| warning: false
#| message: false

augmented_table <- read_tsv("../data/03_augmented_table.tsv")
augmented_metadata <- read_tsv("../data/03_augmented_metadata.tsv")
PCA_ready_table <- read_tsv("../data/03_augmented_table_PCA.tsv")
```

```{r}
augmented_metadata |>
  mutate(Gender = factor(Gender),
         Cohort = factor(Batch)) |>
  table1(x = formula(~ Gender + Age + Localisation + TLS_status | IDH_status),
         data = _)
```

```{r}
# head(augmented_table)
# str(augmented_table)
```

```{r}
# expr_mat <- augmented_table %>%
#   select(Sample_names, GeneFeature, CPM) %>%
#   pivot_wider(
#     names_from  = GeneFeature,   # each gene -> one column
#     values_from = CPM
#   ) %>%
#   column_to_rownames("Sample_names") %>%
#   as.matrix()

# expr_mat[is.na(expr_mat)] <- 0
```

```{r}
# pca_res <- prcomp(expr_mat, center = TRUE, scale. = TRUE)
# 
# summary(pca_res)        # variance explained
# head(pca_res$x)         # PC scores for samples
```

```{r}
# meta <- augmented_table %>%
#   select(Sample_names, Patient, IDH_status, Localisation,
#          Primary_or_Recurrent, Age, Gender, Batch,
#          TLS_status, B_cell_aggregation, Age_groups) %>%
#   distinct()
# 
# scores <- as.data.frame(pca_res$x) %>%
#   rownames_to_column("Sample_names") %>%
#   left_join(meta, by = "Sample_names")
```

```{r}
# ggplot(scores, aes(PC1, PC2, color = IDH_status)) +
#   geom_point() +
#   theme_minimal()
```

```{r}
# data.pca <- princomp(numerical_data)
# summary(data.pca)
# PCA(numerical_data)
```

```{r}
# data.pca$loadings[, 1:2]
```

```{r}
# fviz_eig(data.pca, addlabels = TRUE)
# fviz_pca_var(data.pca, col.var = "black")
# fviz_cos2(data.pca, choice = "var", axes = 1:2)
# fviz_pca_var(data.pca, col.var = "cos2",
#             gradient.cols = c("black", "orange", "green"),
#             repel = TRUE)
```

# CLEAN:

```{r}
pca_fit <- PCA_ready_table |> 
  select(where(is.numeric)) |> 
  select(!c(GEP_score, Age, Batch)) |>
  prcomp(scale = TRUE)

pca_for_plots <- pca_fit |> 
  augment(PCA_ready_table)
```

```{r}
pca_for_plots |>
  ggplot(aes(.fittedPC1, .fittedPC2, color = TLS_status)) + 
  geom_point(size = 1.5, alpha=0.5) +
  scale_color_manual(
    values = c(TLS = "#9C0101", control = "blue")
  ) +
  theme_half_open(12) + background_grid() +
  labs(title = "The first two PCs of transcription data, startified by TLS status",
       x = "PC1",
       y = "PC2")
```

```{r}
pca_for_plots |>
  ggplot(aes(.fittedPC1, .fittedPC2, color = IDH_status)) + 
  geom_point(size = 1.5, alpha=0.5) +
  theme_half_open(12) + background_grid() +
  labs(title = "The first two PCs of transcription data, startified by IDH status",
       x = "PC1",
       y = "PC2")
```
